#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Refcount
Version  : 0.08
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-Refcount-0.08.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-Refcount-0.08.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-refcount-perl/libtest-refcount-perl_0.08-3.debian.tar.xz
Summary  : 'assert reference counts on objects'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-Refcount-license
Requires: perl-Test-Refcount-man

%description
NAME
`Test::Refcount' - assert reference counts on objects
SYNOPSIS
use Test::More tests => 2;
use Test::Refcount;

%package license
Summary: license components for the perl-Test-Refcount package.
Group: Default

%description license
license components for the perl-Test-Refcount package.


%package man
Summary: man components for the perl-Test-Refcount package.
Group: Default

%description man
man components for the perl-Test-Refcount package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Test-Refcount-0.08
mkdir -p %{_topdir}/BUILD/Test-Refcount-0.08/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Test-Refcount-0.08/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Test-Refcount
cp LICENSE %{buildroot}/usr/share/doc/perl-Test-Refcount/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Test/Refcount.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Test-Refcount/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Refcount.3
